package com.divyansh.crio.xmeme.Entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import org.hibernate.annotations.NaturalId;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@Entity
@ApiModel(description = "Entity to create/update a Meme")
public class XmemeEntity {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(unique = true, nullable = false, updatable = false, name = "id")
	@ApiModelProperty(notes = "*Unique Autogenerated ID for a Meme", example = "1")
	private Long id;

	@NaturalId
	@Column(unique = true, nullable = false)
	@ApiModelProperty(notes = "*Unique Owner name for a Meme", example = "Divyansh")
	private String name;

	@NaturalId(mutable=true)
	@Column(unique = true, nullable = false)
	@ApiModelProperty(notes = "*Unique Meme URL must be image link", example = "https://ichef.bbci.co.uk/images/ic/704xn/p072ms6r.jpg")
	private String url;

	@NaturalId(mutable=true)
	@Column(unique = true, nullable = false)
	@ApiModelProperty(notes = "*Unique Meme Caption", example = "Spider Gone LOL")
	private String caption;

	public XmemeEntity() {
	}

	public XmemeEntity(final String name, final String url, final String caption) {
		this.name = name;
		this.url = url;
		this.caption = caption;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getCaption() {
		return caption;
	}

	public void setCaption(String caption) {
		this.caption = caption;
	}	

	@Override
	public String toString() {
		return "XmemeEntity {Id=" + id + ", name=" + name + ", url=" + url + ", caption=" + caption + "}";
	}

}
