package com.divyansh.crio.xmeme.Entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import org.hibernate.annotations.NaturalId;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Entity Class 
 * Contains methods and constructor for multiple attributes required by MEME operations
 * 
 * @author Divyansh Rahangdale
 *
 */
@Entity
@ApiModel(description = "Entity to create/update a Meme")
public class XmemeEntity {

	// Declare the id variable of GenerationType Automatic
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(unique = true, nullable = false, updatable = false, name = "id")
	@ApiModelProperty(notes = "*Unique Autogenerated ID for a Meme", example = "1")
	private Long id;

	// Declare the name variable which will store meme owner name
	@NaturalId
	@Column(unique = true, nullable = false)
	@ApiModelProperty(notes = "*Unique Owner name for a Meme", example = "Divyansh")
	private String name;

	//Declare the url variable which will store meme url
	@NaturalId(mutable=true)
	@Column(unique = true, nullable = false)
	@ApiModelProperty(notes = "*Unique Meme URL must be image link", example = "https://ichef.bbci.co.uk/images/ic/704xn/p072ms6r.jpg")
	private String url;

	//Declare the caption variable which will store meme caption
	@NaturalId(mutable=true)
	@Column(unique = true, nullable = false)
	@ApiModelProperty(notes = "*Unique Meme Caption", example = "Spider Gone LOL")
	private String caption;

	// Default constructor
	public XmemeEntity() {
	}

	// Parameterized constructor
	public XmemeEntity(final String name, final String url, final String caption) {
		this.name = name;
		this.url = url;
		this.caption = caption;
	}

	// GETTER method Id
	public Long getId() {
		return id;
	}

	// SETTER method Id
	public void setId(Long id) {
		this.id = id;
	}

	// GETTER method Name
	public String getName() {
		return name;
	}

	// SETTER method Name
	public void setName(String name) {
		this.name = name;
	}

	// GETTER method Url
	public String getUrl() {
		return url;
	}

	// SETTER method Url
	public void setUrl(String url) {
		this.url = url;
	}

	// GETTER method Caption
	public String getCaption() {
		return caption;
	}

	// SETTER method Caption
	public void setCaption(String caption) {
		this.caption = caption;
	}	

	@Override
	public String toString() {
		return "XmemeEntity {Id=" + id + ", name=" + name + ", url=" + url + ", caption=" + caption + "}";
	}

}
