version: '3'

services:

  xmeme-postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=xmeme
      - POSTGRES_DB=xmeme
      - POSTGRES_USER=xmeme
    ports:
      - 5432:5432

  xmeme-app:
    image: xmeme-divyansh747
    restart: on-failure
    depends_on:
      - xmeme-postgres
    ports:
      - 8081:8081
      - 8080:8080  
    environment:
      - DATABASE_HOST=xmeme-postgres
      - DATABASE_USER=xmeme
      - DATABASE_PASSWORD=xmeme
      - DATABASE_NAME=xmeme
      - DATABASE_PORT=5432
